# Generated by Django 4.2.7 on 2023-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
